<?php

namespace AppBundle\Repository;

/**
 * boletosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class boletosRepository extends \Doctrine\ORM\EntityRepository
{
}
