<?php

namespace AppBundle\Repository;

/**
 * eventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventosRepository extends \Doctrine\ORM\EntityRepository
{
}
