<?php

namespace AppBundle\Repository;

/**
 * evento_tipo_boletoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evento_tipo_boletoRepository extends \Doctrine\ORM\EntityRepository
{
}
