<?php

namespace AppBundle\Repository;

/**
 * tipos_de_eventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipos_de_eventoRepository extends \Doctrine\ORM\EntityRepository
{
}
